export const INIT_FETCH_POSTS = 'INIT_FETCH_POSTS';
export const INIT_FETCH_POSTS_START = 'INIT_FETCH_POSTS_START';
export const INIT_FETCH_POSTS_SUCCESS = 'INIT_FETCH_POSTS_SUCCESS';
export const INIT_FETCH_POSTS_FAIL = 'INIT_FETCH_POSTS_FAIL';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';

